name: newcomers
channels:
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - numpy=1.26.2
  - pandas=2.1.4
  - python=3.10.13
  - jupyterlab_widgets
  - ipywidgets
  - pip:
      - arrow==1.3.0
      - fastparquet==2023.10.1
      - jupyterlab==4.0.9
      - matplotlib==3.8.2
      - networkx==3.2.1
      - plotly==5.18.0
      - pyarrow==14.0.1
      - seaborn==0.13.0
      - tqdm==4.66.1
      - widgetsnbextension==4.0.9
